apiVersion: v1
kind: Service
metadata:
  name: &service-name m-game-engine
spec:
  type: ClusterIP
  selector:
    app: *service-name
  ports:
    - name: grpc
      port: 60051
      targetPort: 60051
      protocol: TCP