apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name m-highscore
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: emailtovamos/m-highscore:v1
        command: ["./binary"]
        args:
          - --address=:50051