apiVersion: v1
kind: Service
metadata:
  name: &service-name m-highscore
spec:
  type: ClusterIP
  selector:
    app: *service-name
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP